name: Publish par_bgc_argo_pitarch to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install build tools
        run: pip install build twine

      - name: Install dependencies
        run: pip install .  # Ejecutado desde la raíz del repo: PAR_BGC_Argo/

      - name: Build the package
        run: python -m build  # También desde la raíz

      - name: Verify compatibility
        run: python -c "from par_bgc_argo_pitarch import par_from_Ed_380_443_490_555_v5; print('Import successful!')"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
